# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82d87b66d6e06b37d858bce9733f7fc1"
application_url = "https://agricultural-pm-lows-promotional.trycloudflare.com"
embedded = true
name = "Offer Your Price"
handle = "offer-your-price-3"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://agricultural-pm-lows-promotional.trycloudflare.com/auth/callback",
  "https://agricultural-pm-lows-promotional.trycloudflare.com/auth/shopify/callback",
  "https://agricultural-pm-lows-promotional.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "objectstesting.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
