# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "007d5d653dce7e3d07648ce2da83d354"
application_url = "https://candle-berlin-revenge-adds.trycloudflare.com"
embedded = true
name = "Offer Your Price"
handle = "offer-your-price-2"

[build]
include_config_on_deploy = true
dev_store_url = "objectstesting.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://candle-berlin-revenge-adds.trycloudflare.com/auth/callback",
  "https://candle-berlin-revenge-adds.trycloudflare.com/auth/shopify/callback",
  "https://candle-berlin-revenge-adds.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
