# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a718b176799baac9f936e4997cef6a35"
application_url = "https://sku-calculators-building-legislative.trycloudflare.com"
embedded = true
name = "Offer Your Price"
handle = "offer-your-price-3"

[build]
include_config_on_deploy = true
dev_store_url = "objectstesting.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://sku-calculators-building-legislative.trycloudflare.com/auth/callback",
  "https://sku-calculators-building-legislative.trycloudflare.com/auth/shopify/callback",
  "https://sku-calculators-building-legislative.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
