# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5027da63d49ca969b7bbbdf563720986"
application_url = "https://commands-signature-delete-gulf.trycloudflare.com"
embedded = true
name = "pay-your-price"
handle = "pay-your-price-1"

[build]
include_config_on_deploy = true
dev_store_url = "konainraza.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_products, write_discounts"

[auth]
redirect_urls = [
  "https://commands-signature-delete-gulf.trycloudflare.com/auth/callback",
  "https://commands-signature-delete-gulf.trycloudflare.com/auth/shopify/callback",
  "https://commands-signature-delete-gulf.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
